# Generated by Django 4.1.13 on 2025-07-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
    ]
